### ISSUE TITLE
Error at first installation screen

### ISSUE THREAD

**Issue by DavidUnzue** [getkirby-v2/plainkit#2]
When installing Plainkit for the first time, that means, calling the panel for the first time, I get following error messages:
![bildschirmfoto 2015-02-26 um 22 58 55](https://cloud.githubusercontent.com/assets/9588510/6402861/3f492a20-be0b-11e4-9cfe-7fc4593f4620.png)

The folders "/site/accounts", "/assets/avatars" and "thumbs" don't exist, so they can't be writable anyway. Should they be copied from Starterkit? This isn't documented in the readme file.

**Comment by bastianallgeier** [comment]
Just create them yourself and make them writable. Then everything should work fine.
