### ISSUE TITLE
Missing 'avatars' Folder Causes PHP 7 Errors

### ISSUE THREAD

**Issue by luxlogica** [getkirby-v2/plainkit#6]
In Kirby's default 'plainkit' instal there is no account, and no *'avatars'* folder. After installation, even if we create a new user account using the Kirby CLI, the *'avatars'* folder is not created. After creating that initial user account with the CLI, we can actually login, go to the 'Users' page, and look at our newly created user account page. There, we can click on the 'upload new profile picture' link, to upload a new picture, but this operation will fail.

On PHP 7.0.*, it will fail silently - it provides no feedback to the user. It simply does not accept the picture, and the page stays as it was.

On PHP 7.1.*, an error message is output: "A non well formed numeric value encountered" - and the operation fails, too. 

Manually creating the *'avatars'* folder solves the issue. If lack of the folder will cause errors, then perhaps it should be included in the 'plainkit' by default - i.e., an empty folder with a *'.gitkeep'* file would suffice.

**Comment by texnixe** [comment]
There is already an issue in the Panel repo: https://github.com/getkirby/panel/issues/1021

But maybe adding an empty folder like in the Starterkit makes sense.
